# dev.yml
# The marketscan_etl_job bundle target environment for development

targets:
  # The deployment targets. See https://docs.databricks.com/en/dev-tools/bundles/deployment-modes.html
  dev:
    mode: development
    workspace:
      host: https://dbc-926acb48-1c75.cloud.databricks.com