name: geography_census_tigerline_state_pipeline_bronze

concurrency: 1

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  validate:
    name: "Test code and bundle"
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: ./bundles/geography_census_tigerline_state_pipeline_bronze
  
    steps:
      - uses: actions/checkout@v3
      
      - uses: databricks/setup-cli@main

      - run: databricks bundle validate --target prod
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

  deploy:
    name: "Run deploy"
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: ./bundles/geography_census_tigerline_state_pipeline_bronze

    needs:
      - validate

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - name: Deploy bundle
        run: databricks bundle deploy --target prod
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
